In [19]:
# Dataset Created
import pandas as pd
import numpy as np

np.random.seed(42)

# Number of customers
n = 3900

# -----------------------------
# Lists for generating the data
# -----------------------------

items = [
    "Blouse", "Sweater", "Jeans", "Sandals", "Sneakers",
    "Shirt", "Shorts", "Coat", "Handbag", "Shoes",
    "Dress", "Skirt", "Sunglasses", "Pants", "Jacket",
    "T-shirt", "Boots", "Hat", "Scarf", "Hoodie"
]

categories = {
    "Blouse": "Clothing",
    "Sweater": "Clothing",
    "Jeans": "Clothing",
    "Sandals": "Footwear",
    "Sneakers": "Footwear",
    "Shirt": "Clothing",
    "Shorts": "Clothing",
    "Coat": "Outerwear",
    "Handbag": "Accessories",
    "Shoes": "Footwear",
    "Dress": "Clothing",
    "Skirt": "Clothing",
    "Sunglasses": "Accessories",
    "Pants": "Clothing",
    "Jacket": "Outerwear",
    "T-shirt": "Clothing",
    "Boots": "Footwear",
    "Hat": "Accessories",
    "Scarf": "Accessories",
    "Hoodie": "Clothing"
}

locations = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
    "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
    "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana",
    "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
    "New York", "North Carolina", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "Tennessee",
    "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming"
]

colors = [
    "Black", "White", "Gray", "Red", "Blue", "Green",
    "Pink", "Purple", "Orange", "Yellow", "Brown",
    "Beige", "Maroon", "Olive", "Teal", "Turquoise",
    "Silver", "Gold", "Violet", "Charcoal"
]

seasons = ["Spring", "Summer", "Fall", "Winter"]

sizes = ["S", "M", "L", "XL"]

shipping_types = [
    "Standard", "Express", "Free Shipping",
    "Next Day Air", "2-Day Shipping", "Store Pickup"
]

payment_methods = [
    "Credit Card", "Debit Card", "PayPal",
    "Cash", "Venmo", "Bank Transfer"
]

purchase_frequencies = [
    "Weekly", "Fortnightly", "Monthly",
    "Quarterly", "Bi-Weekly", "Annually"
]

# -----------------------------
# Create dataset
# -----------------------------

df = pd.DataFrame()

df["Customer ID"] = range(1, n + 1)

df["Age"] = np.random.randint(18, 71, n)

df["Gender"] = np.random.choice(
    ["Male", "Female"],
    n,
    p=[0.45, 0.55]
)

df["Item Purchased"] = np.random.choice(items, n)

df["Category"] = df["Item Purchased"].map(categories)

df["Purchase Amount (USD)"] = np.random.randint(20, 101, n)

df["Location"] = np.random.choice(locations, n)

df["Size"] = np.random.choice(
    sizes,
    n,
    p=[0.25, 0.40, 0.25, 0.10]
)

df["Color"] = np.random.choice(colors, n)

df["Season"] = np.random.choice(seasons, n)

df["Review Rating"] = np.round(
    np.random.uniform(2.5, 5.0, n),
    1
)

df["Subscription Status"] = np.random.choice(
    ["Yes", "No"],
    n,
    p=[0.35, 0.65]
)

df["Shipping Type"] = np.random.choice(
    shipping_types,
    n
)

df["Discount Applied"] = np.random.choice(
    ["Yes", "No"],
    n,
    p=[0.35, 0.65]
)

df["Promo Code Used"] = np.random.choice(
    ["Yes", "No"],
    n,
    p=[0.30, 0.70]
)

df["Previous Purchases"] = np.random.randint(
    0, 51, n
)

df["Payment Method"] = np.random.choice(
    payment_methods,
    n
)

df["Frequency of Purchases"] = np.random.choice(
    purchase_frequencies,
    n
)

# -----------------------------
# Add 37 missing review ratings
# -----------------------------

missing_indices = np.random.choice(
    df.index,
    37,
    replace=False
)

df.loc[missing_indices, "Review Rating"] = np.nan

# -----------------------------
# Save as Excel
# -----------------------------

file_name = "Customer_Shopping_Behavior_Dataset.xlsx"

df.to_excel(
    file_name,
    index=False,
    sheet_name="Customer Data"
)

# -----------------------------
# Confirmation
# -----------------------------
import pandas as pd
import numpy as np

np.random.seed(42)

# Number of customers
n = 3900

# -----------------------------
# Lists for generating the data
# -----------------------------

items = [
    "Blouse", "Sweater", "Jeans", "Sandals", "Sneakers",
    "Shirt", "Shorts", "Coat", "Handbag", "Shoes",
    "Dress", "Skirt", "Sunglasses", "Pants", "Jacket",
    "T-shirt", "Boots", "Hat", "Scarf", "Hoodie"
]

categories = {
    "Blouse": "Clothing",
    "Sweater": "Clothing",
    "Jeans": "Clothing",
    "Sandals": "Footwear",
    "Sneakers": "Footwear",
    "Shirt": "Clothing",
    "Shorts": "Clothing",
    "Coat": "Outerwear",
    "Handbag": "Accessories",
    "Shoes": "Footwear",
    "Dress": "Clothing",
    "Skirt": "Clothing",
    "Sunglasses": "Accessories",
    "Pants": "Clothing",
    "Jacket": "Outerwear",
    "T-shirt": "Clothing",
    "Boots": "Footwear",
    "Hat": "Accessories",
    "Scarf": "Accessories",
    "Hoodie": "Clothing"
}

locations = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
    "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
    "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana",
    "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
    "New York", "North Carolina", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "Tennessee",
    "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming"
]

colors = [
    "Black", "White", "Gray", "Red", "Blue", "Green",
    "Pink", "Purple", "Orange", "Yellow", "Brown",
    "Beige", "Maroon", "Olive", "Teal", "Turquoise",
    "Silver", "Gold", "Violet", "Charcoal"
]

seasons = ["Spring", "Summer", "Fall", "Winter"]

sizes = ["S", "M", "L", "XL"]

shipping_types = [
    "Standard", "Express", "Free Shipping",
    "Next Day Air", "2-Day Shipping", "Store Pickup"
]

payment_methods = [
    "Credit Card", "Debit Card", "PayPal",
    "Cash", "Venmo", "Bank Transfer"
]

purchase_frequencies = [
    "Weekly", "Fortnightly", "Monthly",
    "Quarterly", "Bi-Weekly", "Annually"
]

# -----------------------------
# Create dataset
# -----------------------------

df = pd.DataFrame()

df["Customer ID"] = range(1, n + 1)

df["Age"] = np.random.randint(18, 71, n)

df["Gender"] = np.random.choice(
    ["Male", "Female"],
    n,
    p=[0.45, 0.55]
)

df["Item Purchased"] = np.random.choice(items, n)

df["Category"] = df["Item Purchased"].map(categories)

df["Purchase Amount (USD)"] = np.random.randint(20, 101, n)

df["Location"] = np.random.choice(locations, n)

df["Size"] = np.random.choice(
    sizes,
    n,
    p=[0.25, 0.40, 0.25, 0.10]
)

df["Color"] = np.random.choice(colors, n)

df["Season"] = np.random.choice(seasons, n)

df["Review Rating"] = np.round(
    np.random.uniform(2.5, 5.0, n),
    1
)

df["Subscription Status"] = np.random.choice(
    ["Yes", "No"],
    n,
    p=[0.35, 0.65]
)

df["Shipping Type"] = np.random.choice(
    shipping_types,
    n
)

df["Discount Applied"] = np.random.choice(
    ["Yes", "No"],
    n,
    p=[0.35, 0.65]
)

df["Promo Code Used"] = np.random.choice(
    ["Yes", "No"],
    n,
    p=[0.30, 0.70]
)

df["Previous Purchases"] = np.random.randint(
    0, 51, n
)

df["Payment Method"] = np.random.choice(
    payment_methods,
    n
)

df["Frequency of Purchases"] = np.random.choice(
    purchase_frequencies,
    n
)

# -----------------------------
# Add 37 missing review ratings
# -----------------------------

missing_indices = np.random.choice(
    df.index,
    37,
    replace=False
)

df.loc[missing_indices, "Review Rating"] = np.nan

# -----------------------------
# Save as Excel
# -----------------------------

file_name = "Customer_Shopping_Behavior_Dataset.xlsx"

df.to_excel(
    file_name,
    index=False,
    sheet_name="Customer Data"
)

# -----------------------------
# Confirmation
# -----------------------------

In [20]:
print("======================================")
print("EXCEL DATASET CREATED SUCCESSFULLY")
print("======================================")
print("File:", file_name)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("======================================")

display(df.head(10))

======================================
EXCEL DATASET CREATED SUCCESSFULLY
======================================
File: Customer_Shopping_Behavior_Dataset.xlsx
Rows: 3900
Columns: 18
======================================

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,56,Male,Shirt,Clothing,40,Iowa,M,White,Winter,3.6,Yes,Store Pickup,No,Yes,14,Venmo,Fortnightly
1,2,69,Female,Dress,Clothing,72,Rhode Island,L,Charcoal,Fall,3.0,No,Express,No,Yes,40,PayPal,Weekly
2,3,46,Male,Coat,Outerwear,95,Michigan,S,Black,Spring,4.2,No,2-Day Shipping,Yes,Yes,39,Credit Card,Monthly
3,4,32,Female,Skirt,Clothing,73,Virginia,L,Teal,Summer,3.5,No,Next Day Air,Yes,Yes,25,Bank Transfer,Bi-Weekly
4,5,60,Female,Sweater,Clothing,76,New York,S,Pink,Fall,2.8,Yes,2-Day Shipping,No,No,13,Debit Card,Monthly
5,6,25,Female,Handbag,Accessories,39,Maryland,M,Gold,Fall,2.8,No,2-Day Shipping,No,No,11,Cash,Quarterly
6,7,38,Female,Jacket,Outerwear,68,Oregon,S,Yellow,Summer,3.3,No,Standard,Yes,No,26,PayPal,Quarterly
7,8,56,Male,Sweater,Clothing,26,North Carolina,S,Teal,Spring,4.4,Yes,Standard,No,No,46,PayPal,Fortnightly
8,9,36,Female,Blouse,Clothing,48,Iowa,S,Blue,Summer,2.6,No,Standard,No,No,30,Bank Transfer,Bi-Weekly
9,10,40,Male,Shoes,Footwear,67,West Virginia,S,Brown,Winter,3.1,No,Store Pickup,No,No,3,Debit Card,Quarterly

In [21]:
df.describe()#numerical statistics of numerical column only

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.087436,59.971538,3.766451,24.615641
std,1125.977353,15.215450,23.434398,0.725280,14.709017
min,1.000000,18.000000,20.000000,2.500000,0.000000
25%,975.750000,31.000000,40.000000,3.100000,12.000000
50%,1950.500000,44.000000,59.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,37.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [22]:
df.describe(include='all')#for categorical column too

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,20,4,NaN,48,4,20,4,NaN,2,6,2,2,NaN,6,6
top,NaN,NaN,Female,T-shirt,Clothing,NaN,Wyoming,M,Red,Spring,NaN,No,Next Day Air,No,No,NaN,Bank Transfer,Weekly
freq,NaN,NaN,2094,229,1934,NaN,109,1563,231,1034,NaN,2575,689,2508,2729,NaN,673,657
mean,1950.500000,44.087436,NaN,NaN,NaN,59.971538,NaN,NaN,NaN,NaN,3.766451,NaN,NaN,NaN,NaN,24.615641,NaN,NaN
std,1125.977353,15.215450,NaN,NaN,NaN,23.434398,NaN,NaN,NaN,NaN,0.725280,NaN,NaN,NaN,NaN,14.709017,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,40.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,12.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,37.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int32
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int32
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int32
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int32(3), int64(1), object(13)
memory usage: 502.9+ KB

In [24]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

Review rating has 37 null values - replaced with mean or median?(mean get affected by outliers and that would skewed the distribution of our data but median is robust to outlers. Filling all the values with median technically works but it is not the best practice why because rating is varies a lot depending upon the category. Clothing category have different review rating than footwear category if we fill it everywhere we are basically forcing clothing review rating as footwear items and that could introduce biased in the dataset. instead what we will impute the missing values using the median review rating within each category. which means we will find out the missing value in each category and fill it with median of that category only. if a footwear item has a missing value it is filled by median of footwear item not by clothing item

In [25]:
df['Review Rating'] = df['Review Rating'].fillna(df.groupby('Category')['Review Rating'].transform('median'))

In [26]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

This is the difference between cleaning the data to get it done vs cleaning the data rightway but what I have done taking time to analyse and to respect the natural difference between categories which gives us more accurate and trustworthy data.

snake casing = smaller cases with underscore so that we do not have to remember the column name always while writing the code as they are in upper and lower cases or with special characters

In [27]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [28]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [29]:
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount_'})

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [31]:
# creating new column age_group
labels = ['Young', 'Adult', 'Middle-Aged', 'Senior']
# Categorize the age column using pd.cu
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [32]:
df[['age','age_group']].head(10)

   age    age_group
0   56  Middle-Aged
1   69       Senior
2   46  Middle-Aged
3   32        Adult
4   60       Senior
5   25        Young
6   38        Adult
7   56  Middle-Aged
8   36        Adult
9   40        Adult

In [33]:
# Creating column purchase_frequency_days(converting text into number like fotnightly into 14)
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [34]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                        7                 Weekly
2                       30                Monthly
3                       14              Bi-Weekly
4                       30                Monthly
5                       90              Quarterly
6                       90              Quarterly
7                       14            Fortnightly
8                       14              Bi-Weekly
9                       90              Quarterly

In [35]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0               No             Yes
1               No             Yes
2              Yes             Yes
3              Yes             Yes
4               No              No
5               No              No
6              Yes              No
7               No              No
8               No              No
9               No              No

moving data to Mysql

In [36]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\user\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [37]:
from sqlalchemy import create_engine
# Mysql connection
username = "root"
password = "Myrohitsql1489*"
host  = "localhost"
port = "3306"
database = "customer_behaviour"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#dataframe to Mysql
table_name = "mytable"
df.to_sql(table_name, engine, if_exists="replace", index=False)

#read back sample
pd.read_sql("SELECT * FROM mytable limit 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount_,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,56,Male,Shirt,Clothing,40,Iowa,M,White,Winter,3.6,Yes,Store Pickup,No,Yes,14,Venmo,Fortnightly,Middle-Aged,14
1,2,69,Female,Dress,Clothing,72,Rhode Island,L,Charcoal,Fall,3.0,No,Express,No,Yes,40,PayPal,Weekly,Senior,7
2,3,46,Male,Coat,Outerwear,95,Michigan,S,Black,Spring,4.2,No,2-Day Shipping,Yes,Yes,39,Credit Card,Monthly,Middle-Aged,30
3,4,32,Female,Skirt,Clothing,73,Virginia,L,Teal,Summer,3.5,No,Next Day Air,Yes,Yes,25,Bank Transfer,Bi-Weekly,Adult,14
4,5,60,Female,Sweater,Clothing,76,New York,S,Pink,Fall,2.8,Yes,2-Day Shipping,No,No,13,Debit Card,Monthly,Senior,30